### ISSUE TITLE
($array) must be of type array, null given

### ISSUE THREAD

**Issue by iio7** [dokufreaks/plugin-discussion#320]
I have just upgraded the plugin today and get the following error when I create a new fresh page and inserts the `~~DISCUSSION~~` tag:

```
TypeError: array_keys(): Argument #1 ($array) must be of type array, null given

An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the discussion plugin.

More info has been written to the DokuWiki error log.
```

And in the error log it says:

```
2021-03-21 23:46:24TypeError: array_keys(): Argument #1 ($array) must be of type array, null given /lib/plugins/discussion/action.php(422)
#0 /lib/plugins/discussion/action.php(422): array_keys(NULL)
#0 /lib/plugins/discussion/action.php(422): array_keys(NULL)
#1 /lib/plugins/discussion/action.php(334): action_plugin_discussion->_show(NULL)
#2 /inc/Extension/EventHandler.php(81): action_plugin_discussion->comments(Object(dokuwiki\Extension\Event), Array)
#3 /inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'AFTER')
#4 /inc/Extension/Event.php(136): dokuwiki\Extension\Event->advise_after()
#5 /inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
#6 /inc/template.php(84): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
#7 /lib/tpl/dokuwiki/main.php(58): tpl_content()
#8 /inc/actions.php(27): include('...')
#9 /doku.php(122): act_dispatch()
#10 {main}
```

It still works on old discussions, but creating new pages creates the issue.

**Comment by iio7** [comment]
I have just discovered this is only an issue on PHP 8. The machine got upgraded and it is now running PHP 8.

**Comment by mprins** [comment]
actually it is on this line: https://github.com/dokufreaks/plugin-discussion/blob/c348236f67b197dbc0aae39f168b0f2eb250f610/action.php#L419

```
TypeError: array_keys(): Argument #1 ($array) must be of type array, null given
/XXXXXX/www/dokuwiki/lib/plugins/discussion/action.php(419)
#0 /XXXXXX/www/dokuwiki/lib/plugins/discussion/action.php(419): array_keys()
#1 /XXXXXX/www/dokuwiki/lib/plugins/discussion/action.php(331): action_plugin_discussion->_show()
#2 /XXXXXX/www/dokuwiki/inc/Extension/EventHandler.php(81): action_plugin_discussion->comments()
#3 /XXXXXX/www/dokuwiki/inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event()
#4 /XXXXXX/www/dokuwiki/inc/Extension/Event.php(136): dokuwiki\Extension\Event->advise_after()
#5 /XXXXXX/www/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
#6 /XXXXXX/www/dokuwiki/inc/template.php(84): dokuwiki\Extension\Event::createAndTrigger()
#7 /XXXXXX/www/dokuwiki/lib/tpl/wildwater/main.php(146): tpl_content()
#8 /XXXXXX/www/dokuwiki/inc/actions.php(27): include('...')
#9 /XXXXXX/www/dokuwiki/doku.php(122): act_dispatch()
#10 {main}
```

**Comment by mprins** [comment]
Created https://github.com/dokufreaks/plugin-discussion/pull/323 to fix this
