### ISSUE TITLE
Dokuwiki Igor/Php 8: Error with null for array_keys

### ISSUE THREAD

**Issue by ppoilbarbe** [dokufreaks/plugin-discussion#334]
With any page with discussion, since I migrated from dokuwiki Hogfather to Igor and Php 7 -> php 8, there is an error in discussion plugin.
Here is the error log content (actual path for root directory is changed):

```
2022-10-17 09:47:27	$ROOT/lib/plugins/discussion/action.php(419)	TypeError: array_keys(): Argument #1 ($array) must be of type array, null given
  #0 $ROOT/lib/plugins/discussion/action.php(419): array_keys()
  #1 $ROOT/lib/plugins/discussion/action.php(331): action_plugin_discussion->_show()
  #2 $ROOT/inc/Extension/EventHandler.php(81): action_plugin_discussion->comments()
  #3 $ROOT/inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event()
  #4 $ROOT/inc/Extension/Event.php(136): dokuwiki\Extension\Event->advise_after()
  #5 $ROOT/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
  #6 $ROOT/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
  #7 $ROOT/lib/tpl/dokuwiki/main.php(59): tpl_content()
  #8 $ROOT/inc/actions.php(27): include('...')
  #9 $ROOT/doku.php(126): act_dispatch()
  #10 {main}
```
Environment:
* System: Ubuntu 22.04
* Apache: 2.4.52-1ubuntu4.1
* libApache2-mod-php: 8.1.2-1ubuntu2.5
* php-sqlite3: 2:8.1+92ubuntu1
* libsqlite3-0:  3.37.2-2

**Comment by Klap-in** [comment]
My impression is that current version of the discussion plugin fixes this already. Could use 'Reinstall' in the Extension Manager, to ensure you have that version?

Alternatively, I prepared an update, see pull request #333. I expect this issue is solved there in different manner.
It can be tested with https://github.com/dokufreaks/plugin-discussion/archive/refs/heads/cleanup.zip
