### ISSUE TITLE
deprecated logs

### ISSUE THREAD

**Issue by NbverHub** [dokufreaks/plugin-discussion#346]
Hi!
In the View Logs-deprecated of dokuwiki, the following are being identified:

`utf8_strtolower() is deprecated. It was called from action_plugin_discussion::comment_phrase_match() in .../plugins/discussion/action.php:1640 dokuwiki\Utf8\PhpString::strtolower() should be used instead!`

There is no big problem in using the wiki, but the log keeps piling up unnecessarily.
I want you to update to solve this.

**Comment by KaiMartin** [comment]
I see quite a few warnings concerning ptln():
   ptln() is deprecated. It was called from action_plugin_discussion::showDiscussionSection() in /.../lib/plugins/discussion/action.php:470 echo should be used instead!
   
We are using PHP 8.2

**Comment by Ragos81** [comment]
I also get a huge amount of warnings and errors in the log, some examples:

> 2024-08-26 05:29:55
E_WARNING: Undefined array key "comment"
/var/www/html/lib/plugins/discussion/action.php(222)
#0 /var/www/html/lib/plugins/discussion/action.php(222): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/inc/Extension/EventHandler.php(80): action_plugin_discussion->handle_act_preprocess()
#2 /var/www/html/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event()
#3 /var/www/html/inc/ActionRouter.php(83): dokuwiki\Extension\Event->advise_before()
#4 /var/www/html/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
#5 /var/www/html/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
#6 /var/www/html/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
#7 /var/www/html/doku.php(131): act_dispatch()
#8 {main}

> 2024-08-26 05:27:04
E_WARNING: Undefined array key "title"
/var/www/html/lib/plugins/discussion/action.php(427)
#0 /var/www/html/lib/plugins/discussion/action.php(427): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/lib/plugins/discussion/action.php(331): action_plugin_discussion->_show()
#2 /var/www/html/inc/Extension/EventHandler.php(80): action_plugin_discussion->comments()
#3 /var/www/html/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
#4 /var/www/html/inc/Extension/Event.php(137): dokuwiki\Extension\Event->advise_after()
#5 /var/www/html/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#6 /var/www/html/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
#7 /var/www/html/lib/tpl/dokuwiki/main.php(60): tpl_content()
#8 /var/www/html/inc/actions.php(30): include('...')
#9 /var/www/html/doku.php(131): act_dispatch()
#10 {main}

> 2024-08-26 05:27:04
E_WARNING: Undefined array key "reply"
/var/www/html/lib/plugins/discussion/action.php(324)
#0 /var/www/html/lib/plugins/discussion/action.php(324): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/inc/Extension/EventHandler.php(80): action_plugin_discussion->comments()
#2 /var/www/html/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
#3 /var/www/html/inc/Extension/Event.php(137): dokuwiki\Extension\Event->advise_after()
#4 /var/www/html/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#5 /var/www/html/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
#6 /var/www/html/lib/tpl/dokuwiki/main.php(60): tpl_content()
#7 /var/www/html/inc/actions.php(30): include('...')
#8 /var/www/html/doku.php(131): act_dispatch()
#9 {main}

> 2024-08-26 05:27:04
E_WARNING: Undefined array key "cid"
/var/www/html/lib/plugins/discussion/action.php(322)
#0 /var/www/html/lib/plugins/discussion/action.php(322): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/inc/Extension/EventHandler.php(80): action_plugin_discussion->comments()
#2 /var/www/html/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
#3 /var/www/html/inc/Extension/Event.php(137): dokuwiki\Extension\Event->advise_after()
#4 /var/www/html/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#5 /var/www/html/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
#6 /var/www/html/lib/tpl/dokuwiki/main.php(60): tpl_content()
#7 /var/www/html/inc/actions.php(30): include('...')
#8 /var/www/html/doku.php(131): act_dispatch()
#9 {main}

> 2024-08-26 05:27:04
E_WARNING: Undefined array key 1
/var/www/html/lib/plugins/mediathumbnails/syntax.php(86)
#0 /var/www/html/lib/plugins/mediathumbnails/syntax.php(86): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/inc/parser/renderer.php(126): syntax_plugin_mediathumbnails->render()
#2 /var/www/html/inc/parserutils.php(691): Doku_Renderer->plugin()
#3 /var/www/html/inc/parserutils.php(158): p_render()
#4 /var/www/html/inc/parserutils.php(97): p_cached_output()
#5 /var/www/html/inc/Ui/PageView.php(67): p_wiki_xhtml()
#6 /var/www/html/inc/Action/Show.php(40): dokuwiki\Ui\PageView->show()
#7 /var/www/html/inc/template.php(120): dokuwiki\Action\Show->tplContent()
#8 [internal function]: tpl_content_core()
#9 /var/www/html/inc/Extension/Event.php(134): call_user_func_array()
#10 /var/www/html/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#11 /var/www/html/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
#12 /var/www/html/lib/tpl/dokuwiki/main.php(60): tpl_content()
#13 /var/www/html/inc/actions.php(30): include('...')
#14 /var/www/html/doku.php(131): act_dispatch()
#15 {main}

> 2024-08-26 05:27:03
E_WARNING: Undefined array key 0
/var/www/html/lib/plugins/openlayersmap/syntax/olmap.php(95)
#0 /var/www/html/lib/plugins/openlayersmap/syntax/olmap.php(95): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/inc/parser/handler.php(298): syntax_plugin_openlayersmap_olmap->handle()
#2 /var/www/html/inc/Parsing/Lexer/Lexer.php(269): Doku_Handler->plugin()
#3 /var/www/html/inc/Parsing/Lexer/Lexer.php(196): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
#4 /var/www/html/inc/Parsing/Lexer/Lexer.php(146): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
#5 /var/www/html/inc/Parsing/Parser.php(113): dokuwiki\Parsing\Lexer\Lexer->parse()
#6 /var/www/html/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse()
#7 /var/www/html/inc/parserutils.php(198): p_get_instructions()
#8 /var/www/html/inc/parserutils.php(520): p_cached_instructions()
#9 /var/www/html/inc/parserutils.php(299): p_render_metadata()
#10 /var/www/html/lib/plugins/publish/helper.php(138): p_get_metadata()
#11 /var/www/html/lib/plugins/publish/helper.php(118): helper_plugin_publish->getMeta()
#12 /var/www/html/lib/plugins/publish/helper.php(197): helper_plugin_publish->getApprovals()
#13 /var/www/html/lib/plugins/publish/helper.php(218): helper_plugin_publish->getSortedApprovedRevisions()
#14 /var/www/html/lib/plugins/publish/helper.php(302): helper_plugin_publish->getLatestApprovedRevision()
#15 /var/www/html/lib/plugins/publish/helper.php(309): helper_plugin_publish->isHidden()
#16 /var/www/html/lib/plugins/publish/action/hide.php(48): helper_plugin_publish->isHiddenForUser()
#17 /var/www/html/inc/Extension/EventHandler.php(80): action_plugin_publish_hide->hidePage()
#18 /var/www/html/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event()
#19 /var/www/html/inc/Extension/Event.php(133): dokuwiki\Extension\Event->advise_before()
#20 /var/www/html/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#21 /var/www/html/inc/pageutils.php(627): dokuwiki\Extension\Event::createAndTrigger()
#22 /var/www/html/lib/plugins/indexmenu/Search.php(354): isHiddenPage()
#23 /var/www/html/inc/search.php(71): dokuwiki\plugin\indexmenu\Search->searchIndexmenuItems()
#24 /var/www/html/inc/search.php(66): search()
#25 /var/www/html/lib/plugins/indexmenu/Search.php(242): search()
#26 /var/www/html/lib/plugins/indexmenu/syntax/indexmenu.php(510): dokuwiki\plugin\indexmenu\Search->search()
#27 /var/www/html/lib/plugins/indexmenu/syntax/indexmenu.php(466): syntax_plugin_indexmenu_indexmenu->buildHtmlIndexmenu()
#28 /var/www/html/inc/parser/renderer.php(126): syntax_plugin_indexmenu_indexmenu->render()
#29 /var/www/html/inc/parserutils.php(691): Doku_Renderer->plugin()
#30 /var/www/html/inc/parserutils.php(158): p_render()
#31 /var/www/html/inc/parserutils.php(97): p_cached_output()
#32 /var/www/html/inc/template.php(1658): p_wiki_xhtml()
#33 /var/www/html/lib/tpl/dokuwiki/main.php(44): tpl_include_page()
#34 /var/www/html/inc/actions.php(30): include('...')
#35 /var/www/html/doku.php(131): act_dispatch()
#36 {main}

Also a lot of deprecated messages, usual with different line numbers of the debug.php:

> ptln() is deprecated. It was called from action_plugin_publish_debug::debug() in /var/www/html/lib/plugins/publish/action/debug.php:22 echo should be used instead!
